CREATE TABLE SERVICECLIENTS (
	ID INT NOT NULL AUTO_INCREMENT,
	FIRSTNAME VARCHAR(100) NOT NULL,
	LASTNAME VARCHAR(100) NOT NULL,
	CREATIONDATE DATE,
	SERVICEDOCUMENTID INT,
	CLIENTADDRESS VARCHAR(300),
	PRIMARY KEY (ID),
	FOREIGN KEY (SERVICEDOCUMENTID) REFERENCES SERVICEDOCUMENT(ID)

)