CREATE TABLE ITEM (
	ID int AUTO_INCREMENT,
	BARCODE int ,
	LOCATIONID int,
	SUBCATEGORYID int,
	VENDORID int,
	TAXRATEID int,
	DESCRIPTION VARCHAR(200),
	WEIGHT VARCHAR(20),
	LASTRECEIVEDDATE DATE,
	ITEMTYPEID INT,
	WARRANTYRETURNS int,
	ACTIVITYSTATUS INT,
	NAME VARCHAR(100),
	PRODUCTINDEX INT<
	PRIMARY KEY (ID),
	FOREIGN KEY (LOCATIONID) REFERENCES LOCATION(ID),
	FOREIGN KEY (SUBCATEGORYID) REFERENCES  SUBCATEGORY(ID),
	FOREIGN KEY (VENDORID) REFERENCES VENDOR(ID),
	FOREIGN KEY (TAXRATEID) REFERENCES TAXRATE(ID),
	FOREIGN KEY (ITEMTYPEID) REFERENCES ITEMTYPE(ID)

)