CREATE TABLE SERVICEDOCUMENT (
	ID int NOT NULL AUTO_INCREMENT,
	DOCUMENTDATE DATE,
	CLIENTNAME VARCHAR(100) NOT NULL,
	CLIENTSURENAME VARCHAR(100) NOT NULL,
	CLIENTADDRESS VARCHAR(300) NOT NULL,
	EMPLOYEENAME VARCHAR(100) NOT NULL,
	EMPLOYEESURNAME VARCHAR(100) NOT NULL,
	EMPLOYEEID int NOT NULL,
	DEVICETYPE VARCHAR(200),
	DEVICEBRAND VARCHAR(200),
	DEVICEMODEL VARCHAR(200),
	DESCRIPTION VARCHAR(10000),
	PRIMARY KEY (ID),
	FOREIGN KEY (EMPLOYEEID) REFERENCES USERDATA(ID)
);