CREATE TABLE SESSION (
	ID int NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(40) NOT NULL ,
	USERID int NOT NULL,
	STATUS int CHECK (STATUS=1 or STATUS=0),
	GUID VARCHAR(100),
	PRIMARY KEY (ID),
	FOREIGN KEY (USERID) REFERENCES USERLOGIN(USERID)
)