CREATE TABLE VENDOR (
	ID int AUTO_INCREMENT,
	BUSINESSNAME VARCHAR(200),
	CONTACTNAME VARCHAR(200),
	ADDRESS1 VARCHAR(200),
	ADDRESS2 VARCHAR(200),
	CITY VARCHAR(50),
	VOIVODESHIP VARCHAR(80),
	POSTCODE VARCHAR(20),
	COUNTRY VARCHAR(40),
	PHONE VARCHAR(40),
	EMAIL VARCHAR(40),
	NOTES VARCHAR(100),
	FAX VARCHAR(40),
	MOBILE VARCHAR(40),
	SUBMITEDDATE DATE,
	PRIMARY KEY (ID)
)